### PR TITLE
Added support for attributed strings

### PR DESCRIPTION
**Pull request by zigadolar**

### CODE REVIEW

**Comment by zigadolar** [comment]
Only supported in iOS6 , where UILabel supports attributed strings.

**Comment by kreeger** [comment]
Thanks for this! I think it's okay for us to define iOS 6 as a base requirement — it's been out long enough! Can you bring in the latest changes from `master` so I can merge this in?

**Comment by zigadolar** [comment]
No problem. Merged in changes from `master`.

**Comment by kreeger** [comment]
Thanks!

**Pull request merged**
